import type { Metadata } from "next";
import { Geist, Geist_Mono, Boldonse } from "next/font/google";

import "./globals.css";
import { AppProvider } from "@/context/AppContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const boldonse = Boldonse({
    variable: "--font-boldonse",
    weight: "400",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${boldonse.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <AppProvider>{children}</AppProvider>
            </body>
        </html>
    );
}
